[2024-08-13T23:06:40.748+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_etl_heart_data.obtain_original_data manual__2024-08-13T23:06:40.296149+00:00 [queued]>
[2024-08-13T23:06:40.751+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_etl_heart_data.obtain_original_data manual__2024-08-13T23:06:40.296149+00:00 [queued]>
[2024-08-13T23:06:40.751+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-08-13T23:06:40.757+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): obtain_original_data> on 2024-08-13 23:06:40.296149+00:00
[2024-08-13T23:06:40.759+0000] {standard_task_runner.py:60} INFO - Started process 581 to run task
[2024-08-13T23:06:40.760+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'process_etl_heart_data', 'obtain_original_data', 'manual__2024-08-13T23:06:40.296149+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/etl_process.py', '--cfg-path', '/tmp/tmpqwie6ojc']
[2024-08-13T23:06:40.761+0000] {standard_task_runner.py:88} INFO - Job 3: Subtask obtain_original_data
[2024-08-13T23:06:40.780+0000] {task_command.py:423} INFO - Running <TaskInstance: process_etl_heart_data.obtain_original_data manual__2024-08-13T23:06:40.296149+00:00 [running]> on host 724c87fe0c82
[2024-08-13T23:06:40.808+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Facundo Adrian Lucianna' AIRFLOW_CTX_DAG_ID='process_etl_heart_data' AIRFLOW_CTX_TASK_ID='obtain_original_data' AIRFLOW_CTX_EXECUTION_DATE='2024-08-13T23:06:40.296149+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-13T23:06:40.296149+00:00'
[2024-08-13T23:06:40.809+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venvved697bq --system-site-packages --python=python
[2024-08-13T23:06:40.812+0000] {process_utils.py:186} INFO - Output:
[2024-08-13T23:06:41.045+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.18.final.0-64 in 73ms
[2024-08-13T23:06:41.045+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venvved697bq, clear=False, no_vcs_ignore=False, global=True)
[2024-08-13T23:06:41.045+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-08-13T23:06:41.045+0000] {process_utils.py:190} INFO -     added seed packages: pip==23.3.1, setuptools==69.0.2, wheel==0.42.0
[2024-08-13T23:06:41.046+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-08-13T23:06:41.062+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvved697bq/bin/pip install -r /tmp/venvved697bq/requirements.txt
[2024-08-13T23:06:41.064+0000] {process_utils.py:186} INFO - Output:
[2024-08-13T23:06:41.572+0000] {process_utils.py:190} INFO - Collecting awswrangler==3.6.0 (from -r /tmp/venvved697bq/requirements.txt (line 1))
[2024-08-13T23:06:41.573+0000] {process_utils.py:190} INFO -   Using cached awswrangler-3.6.0-py3-none-any.whl.metadata (23 kB)
[2024-08-13T23:06:41.588+0000] {process_utils.py:190} INFO - Collecting ucimlrepo==0.0.3 (from -r /tmp/venvved697bq/requirements.txt (line 2))
[2024-08-13T23:06:41.589+0000] {process_utils.py:190} INFO -   Using cached ucimlrepo-0.0.3-py3-none-any.whl.metadata (5.2 kB)
[2024-08-13T23:06:41.609+0000] {process_utils.py:190} INFO - Requirement already satisfied: boto3<2.0.0,>=1.20.32 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvved697bq/requirements.txt (line 1)) (1.34.158)
[2024-08-13T23:06:41.609+0000] {process_utils.py:190} INFO - Requirement already satisfied: botocore<2.0.0,>=1.23.32 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvved697bq/requirements.txt (line 1)) (1.34.158)
[2024-08-13T23:06:41.610+0000] {process_utils.py:190} INFO - Requirement already satisfied: numpy<2.0,>=1.18 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvved697bq/requirements.txt (line 1)) (1.24.4)
[2024-08-13T23:06:41.610+0000] {process_utils.py:190} INFO - Requirement already satisfied: packaging<24.0,>=21.1 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvved697bq/requirements.txt (line 1)) (23.2)
[2024-08-13T23:06:41.610+0000] {process_utils.py:190} INFO - Requirement already satisfied: pandas<2.1.0,>=1.2.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvved697bq/requirements.txt (line 1)) (2.0.3)
[2024-08-13T23:06:41.611+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyarrow>=7.0.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvved697bq/requirements.txt (line 1)) (14.0.2)
[2024-08-13T23:06:41.611+0000] {process_utils.py:190} INFO - Requirement already satisfied: typing-extensions<5.0.0,>=4.4.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvved697bq/requirements.txt (line 1)) (4.12.2)
[2024-08-13T23:06:41.614+0000] {process_utils.py:190} INFO - Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/***/.local/lib/python3.8/site-packages (from boto3<2.0.0,>=1.20.32->awswrangler==3.6.0->-r /tmp/venvved697bq/requirements.txt (line 1)) (0.10.0)
[2024-08-13T23:06:41.614+0000] {process_utils.py:190} INFO - Requirement already satisfied: s3transfer<0.11.0,>=0.10.0 in /home/***/.local/lib/python3.8/site-packages (from boto3<2.0.0,>=1.20.32->awswrangler==3.6.0->-r /tmp/venvved697bq/requirements.txt (line 1)) (0.10.2)
[2024-08-13T23:06:41.617+0000] {process_utils.py:190} INFO - Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /home/***/.local/lib/python3.8/site-packages (from botocore<2.0.0,>=1.23.32->awswrangler==3.6.0->-r /tmp/venvved697bq/requirements.txt (line 1)) (2.8.2)
[2024-08-13T23:06:41.618+0000] {process_utils.py:190} INFO - Requirement already satisfied: urllib3<1.27,>=1.25.4 in /home/***/.local/lib/python3.8/site-packages (from botocore<2.0.0,>=1.23.32->awswrangler==3.6.0->-r /tmp/venvved697bq/requirements.txt (line 1)) (1.26.18)
[2024-08-13T23:06:41.654+0000] {process_utils.py:190} INFO - Requirement already satisfied: pytz>=2020.1 in /home/***/.local/lib/python3.8/site-packages (from pandas<2.1.0,>=1.2.0->awswrangler==3.6.0->-r /tmp/venvved697bq/requirements.txt (line 1)) (2023.3.post1)
[2024-08-13T23:06:41.654+0000] {process_utils.py:190} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.8/site-packages (from pandas<2.1.0,>=1.2.0->awswrangler==3.6.0->-r /tmp/venvved697bq/requirements.txt (line 1)) (2023.4)
[2024-08-13T23:06:41.658+0000] {process_utils.py:190} INFO - Requirement already satisfied: six>=1.5 in /home/***/.local/lib/python3.8/site-packages (from python-dateutil<3.0.0,>=2.1->botocore<2.0.0,>=1.23.32->awswrangler==3.6.0->-r /tmp/venvved697bq/requirements.txt (line 1)) (1.16.0)
[2024-08-13T23:06:41.671+0000] {process_utils.py:190} INFO - Using cached awswrangler-3.6.0-py3-none-any.whl (403 kB)
[2024-08-13T23:06:41.673+0000] {process_utils.py:190} INFO - Using cached ucimlrepo-0.0.3-py3-none-any.whl (7.0 kB)
[2024-08-13T23:06:42.945+0000] {process_utils.py:190} INFO - Installing collected packages: ucimlrepo, awswrangler
[2024-08-13T23:06:43.052+0000] {process_utils.py:190} INFO - Successfully installed awswrangler-3.6.0 ucimlrepo-0.0.3
[2024-08-13T23:06:43.113+0000] {process_utils.py:190} INFO - 
[2024-08-13T23:06:43.114+0000] {process_utils.py:190} INFO - [notice] A new release of pip is available: 23.3.1 -> 24.2
[2024-08-13T23:06:43.114+0000] {process_utils.py:190} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2024-08-13T23:06:43.177+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvved697bq/bin/python /tmp/venv-callfl7plfn4/script.py /tmp/venv-callfl7plfn4/script.in /tmp/venv-callfl7plfn4/script.out /tmp/venv-callfl7plfn4/string_args.txt /tmp/venv-callfl7plfn4/termination.log
[2024-08-13T23:06:43.179+0000] {process_utils.py:186} INFO - Output:
[2024-08-13T23:06:45.116+0000] {process_utils.py:190} INFO - [[34m2024-08-13T23:06:45.115+0000[0m] {[34mcredentials.py:[0m1147} INFO[0m - Found credentials in environment variables.[0m
[2024-08-13T23:06:45.142+0000] {process_utils.py:190} INFO - [[34m2024-08-13T23:06:45.142+0000[0m] {[34mconfigprovider.py:[0m952} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2024-08-13T23:06:45.278+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-08-13T23:06:45.286+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=process_etl_heart_data, task_id=obtain_original_data, execution_date=20240813T230640, start_date=20240813T230640, end_date=20240813T230645
[2024-08-13T23:06:45.302+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-08-13T23:06:45.314+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
